### ISSUE TITLE
The first menu item on the API site seems redundant

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/api.backdropcms.org#10]
The menu link "Backdrop 1.X" links to a strange little page with 
```
API reference
Much of this information is actually stored in the advanced help; please check the API topic. This help will primarily be aimed at documenting classes and function calls.

Topics:

The life of a view
Views hooks
About Views handlers
About Views plugins
Views template files
Views module handlers
```

This menu link should be deleted or changed to point to a nice summary of what the API site is about. And this nice summary page should also be the landing page for the API site instead of "Topics".

**Comment by quicksketch** [comment]
Hm, that block seems to be provided by API module itself. Let's convert that to a menu block instead, so we can control the items it displays.

**Comment by quicksketch** [comment]
Hi @docwilmot, I turned that block into a menu (or more accurately re-used the "Navigation" menu). Your account has administer menus permission, so you should be able to rearrange it as needed.

**Comment by docwilmot** [comment]
Better. 
In future a nicer landing page would be good, instead of "Topics".

**Comment by quicksketch** [comment]
The new frontpage on the Backdrop site is the top page of the developer handbook. If we can come up with some more appropriate text, it can now be edited at https://api.backdropcms.org/node/28585/edit.

I think the main issue here is resolved with the navigation link being funky, so closing.
