### ISSUE TITLE
Form API: update the description for the help element

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/api.backdropcms.org#105]
The description of the `'#type' => 'help'` form element in https://api.backdropcms.org/form_api#help says:

> Add some help text to the top of a page.

That is not accurate, as the help element may be rendered anywhere on the form (and also controlled via its `#weight` property).

**Comment by klonos** [comment]
I propose changing it to something like:

> Adds text styled as help text (adds a `help` CSS class to it).

**Comment by BWPanda** [comment]
Updated. I used this wording:

> Add some help text to the page (the element will have a help class and may be styled differently to other text).

Hope that's ok.
