### ISSUE TITLE
Broken links on page of Upgrading from Drupal 7

### ISSUE THREAD

**Issue by VasasA** [backdrop-ops/api.backdropcms.org#111]
The page of [Upgrading from Drupal 7](https://api.backdropcms.org/documentation/upgrading-from-drupal-7) contains two broken links:
- complete list of contributed modules that are no longer necessary
- complete list of modules removed from Backdrop core

Fixed links:
- complete list of contributed modules that are no longer necessary: https://backdropcms.org/node/1683
- complete list of modules removed from Backdrop core : https://api.backdropcms.org/change-records/modules-removed-from-backdrop-which-were-in-drupal-7

**Comment by BWPanda** [comment]
Thanks @VasasA, I've fixed those links.
