### ISSUE TITLE
API tables not remembering pager

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/api.backdropcms.org#12]
The tables on the API site load by Ajax. When you pick a table with a pager, e.g. https://api.backdropcms.org/api/backdrop/functions, and go to any page (say page 4), then click a topic in the page (say, 'backdrop_array_merge_deep'), if you click the browser back button you're dumped back to page 1 again. 
If youre trying to read sequential topics (e.g. I'm learning the views API) that would be annoying: Go to page 4, read something, back to page 1, click page 4 again, wait, click next topic, repeat. Cuss, throw stuff.

**Comment by quicksketch** [comment]
Thanks @docwilmot.

I took a look at this and disabled the AJAX pager ont he list of change records. That was easy. Unfortunately API module defines all of its views as "block" displays, which apparently does not work with exposed filters unless the AJAX option is enabled. There's definitely a way we can fix this, but unfortunately it's not so easy as just changing the view settings.

**Comment by BWPanda** [comment]
As a workaround, I guess just open links in a new tab and keep the table open all the time...

**Comment by jenlampton** [comment]
> Unfortunately API module defines all of its views as "block" displays, which apparently does not work with exposed filters unless the AJAX option is enabled.

Blocks do work with exposed filters now, thanks to adding the features from `views_content` module. I've disabled ajax on these api views and committed them to staging for deploy.
