### ISSUE TITLE
API Site crashes when viewing "admin/content"

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/api.backdropcms.org#13]
As said.

**Comment by quicksketch** [comment]
Thanks, fixed this on the API site. It looks like the exposed filter form's `$form_state` definition exceeded the `max_packet_size` available in MySQL. This seems like it may be a problem for a lot of Backdrop users out there if Views is generating forms that exceed the max packet default of 1MB. I'll file an issue over in the Backdrop issues queue.

For the API site, I just increased this limit from 1MB to 16MB.

**Comment by quicksketch** [comment]
Backdrop CMS issue: https://github.com/backdrop/backdrop-issues/issues/657
