### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#16]
Is there currently a process for allowing us to update the documentation on the API site? If not, will something be put in place? (e.g. node revisions for authenticated users)

I have found a few spelling/grammatical errors while reading through some of the docs and would love to be able to fix them as I go (rather than creating issues here)... Also, since they're nodes, I can't create pull requests.

**Comment by quicksketch** [comment]
Hi @BWPanda! Eventually we'll let users log into the main site at backdropcms.org, and set up a single-sign on between that and the API site (and possibly whatever forum comes to pass).

For now though, we'll just send you an invite and give you the editorial role. :)

**Comment by quicksketch** [comment]
I contacted you via your site contact form. :smile:

**Comment by BWPanda** [comment]
Awesome, thanks.
