### ISSUE TITLE
Layout info file version

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#17]
The [documentation](https://api.backdropcms.org/layouts) says:
> **backdrop version (required)**
`backdrop = 1.x`

> All .info files for modules and layouts must indicate what major version of Backdrop core they are compatible with. The value set here is compared with the [DRUPAL_CORE_COMPATIBILITY](https://api.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/constant/DRUPAL_CORE_COMPATIBILITY/1) constant. If it does not match, the layout will be disabled.

Should that value not be compared with [BACKDROP_VERSION](https://api.backdropcms.org/api/backdrop/core!includes!bootstrap.inc/constant/BACKDROP_VERSION/1) instead?

**Comment by quicksketch** [comment]
Oh! Yes it actually compares against BACKDROP_CORE_COMPATIBILITY, otherwise none of our current layouts would work. :)

Fixed that reference. Thanks!
