### ISSUE TITLE
Add link to print API docs

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/api.backdropcms.org#22]
On D.org you can get a printable view of docs, but here we cant.

**Comment by quicksketch** [comment]
Do you think we need a print link, or just a better print.css stylesheet? I don't think most developers would need a link to open a print dialog.

**Comment by quicksketch** [comment]
Oh, I think you're saying you miss the ability to print the entire book? The print functionality was removed from book in https://github.com/backdrop/backdrop-issues/issues/242, so re-enabling this ability would be fairly involved.

**Comment by docwilmot** [comment]
:grinning: 
Was boarding a flight and wanted to download so I could work on this. Oh well, reasonable decision though.
