### ISSUE TITLE
Add example modules to API docs

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/api.backdropcms.org#23]
Was about to start work on the "Advanced API Documentation" part of [Backdrop developer docs](https://github.com/backdrop-ops/api.backdropcms.org/issues/3#issuecomment-71902056) and realised that essentially, this is what Examples is, and [how its used on D.org](https://api.drupal.org/api/examples/7). 

Can we do this? See the Backdrop port here https://github.com/backdrop-contrib/examples

**Comment by quicksketch** [comment]
Hi @docwilmot, yes we can definitely do this. I'll add examples to the repository checkout.

**Comment by quicksketch** [comment]
Yay, looks like that worked just fine. LMK if there are any issues:

https://api.backdropcms.org/api/backdrop/modules!examples!examples.module/group/examples/1
