### ISSUE TITLE
Errors that popped up while browsing api.backdropcms.org

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/api.backdropcms.org#25]
No idea what I did to get them, I was flipping through tabs when I noticed them pop up.
`Notice: Undefined variable: signature_info in api_page_function() (line 749 of /home/api/www-backdrop/modules/contrib/api/api.pages.inc).`
`Warning: Invalid argument supplied for foreach() in api_page_function() (line 749 of /home/api/www-backdrop/modules/contrib/api/api.pages.inc).`

![image](https://cloud.githubusercontent.com/assets/5607236/9430070/073ec776-49b5-11e5-9de5-45bd1f1a9df8.png)

**Comment by quicksketch** [comment]
Looks like there was an issue in the foreach() loop at that line number. I fixed this and updated our API module to the latest release. This should be fixed now.
