### ISSUE TITLE
./core/scripts/run-tests.sh docs

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/api.backdropcms.org#27]
can you put the output of:

```
./core/scripts/run-tests.sh --help
```
onto api.backdropcms.org?

~Geoff

**Comment by quicksketch** [comment]
If we put it at the top of the file with a `@file` indicator, it will show up at https://api.backdropcms.org/api/backdrop/core!scripts!run-tests.sh/1 (without having to click the "Show source" button). Would that suffice?

**Comment by serundeputy** [comment]
yes; I'll file a PR against /backdrop/backdrop.

thanks!

**Comment by quicksketch** [comment]
New issue at https://github.com/backdrop/backdrop-issues/issues/1343. Thanks @serundeputy!
