### ISSUE TITLE
Create Theme API Corrections

### ISSUE THREAD

**Issue by twmfc** [backdrop-ops/api.backdropcms.org#31]
Hi,
I've just been reviewing Creating Themes within the Backdrop CMS API documentation, specifically [https://api.backdropcms.org/themes] and noticed a few typos and other issues that I've tried to capture here:

_Section:_\* Writing theme .info files*

The use of _DRUPAL_CORE_COMPATIBILITY_ in the following: -

"All .info files for modules and themes must indicate what major version of Backdrop core they are compatible with. The value set here is compared with the DRUPAL_CORE_COMPATIBILITY constant. If it does not match, the theme will be disabled."

Misspelling _Javascriprt_ should be Javascript: -

"Javascriprt files to be included."

_Section: Global Settings_

I'm not sure _D7 diff_ was intended to be left in: -

_Section: Add your custom code in template.php_

Misspelling _templte_ should be template

Further details about adding templte.php functions to be covered in another instruction file.

_Section: Add template files_

The following sentence might be better worded and I'm not sure the references to ‘Converting from 6.x…’ are required?

Current

A single hyphen is still used to separate words: for example, "user-picture.tpl.php" or "node--long-content-type-name.tpl.php", so the double hyphen always indicates a more targeted override of what comes before the "--". See Converting 6.x themes to 7.x for more info.

Proposed

A single hyphen is used to separate words: for example, "user-picture.tpl.php". A double hyphen indicates a more targeted override of what comes before the "--" for example, "node--long-content-type-name.tpl.php". See Converting 6.x themes to 7.x for more info.

_Section: Add your own style_

Misspelling _pecify_ should be specify

If you want to override one of the parent theme's style sheets, pecify a style sheet with the same filename in the sub-theme. For instance, to override page_style.css inherited from a parent theme, add the following line to your sub-theme's .info file:

_General_

I think the section might also benefit by consistent use of the terms for the following:

'parent theme' or 'base theme'

'sub theme', 'subtheme' or sub-theme'

'javascript', 'Javascript' or  'JavaScript'

**Comment by serundeputy** [comment]
> Misspelling Javascriprt should be Javascript: -
  * corrected

> I'm not sure D7 diff was intended to be left in: -
  * updated

> Section: Add your custom code in template.php
  * corrected

> Section: Add template files
  *  updated

> Misspelling pecify should be specify
  * someone else must have got this one already

> General
>I think the section might also benefit by consistent use of the terms for the following:
>'parent theme' or 'base theme'
  * I did not update this as it was not very clear to me on how to do handle it.


>'sub theme', 'subtheme' or sub-theme'
  * updated to `sub-theme`

> 'javascript', 'Javascript' or 'JavaScript'
  * updated to `javascript`

**Comment by BWPanda** [comment]
I've updated the rest.
