### ISSUE TITLE
Typo on /database-configuration page

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/api.backdropcms.org#32]
On the URL: https://api.backdropcms.org/database-configuration

> To configure Backdrop to use a Master/Save configuration, do not specify a simple $database string. Instead, specify an array of database configuration using the $databases (note the plural form) variable.

I think `Master/Save` should be `Master/Slave`.

~Geoff

**Comment by BWPanda** [comment]
Fixed.

**Comment by serundeputy** [comment]
thanks!  closing.
