### ISSUE TITLE
Incorrect info on https://api.backdropcms.org/modules

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/api.backdropcms.org#34]
This sentence:

> Core theme directories are found in the BACKDROP_ROOT/core/modules directory; contributed themes in the BACKDROP_ROOT/modules directory.

Needs some work; I propose:

Core `module` directories are found in the BACKDROP_ROOT/core/modules directory; contributed `modules` in the BACKDROP_ROOT/modules directory.
---

> For example, if it is named "my_module.info", then Backdrop will see the name of the theme as "my_module".

Should be:

For example, if it is named "my_module.info", then Backdrop will see the name of the `module` as "my_module".
---

> Descriptions can contain links to documentation and sources. The following example shows a link to the author. It could be a link to a documentation node on Backdrop.org.

Should this be:

Descriptions can contain links to documentation and sources. The following example shows a link to the author. It could be a link to a documentation node on `Backdropcms.org`.

?
---

> Mdules and themes may specify that they are absolutely required and should never be disabled by adding required = TRUE.

Should be:

`Modules` and themes may specify that they are absolutely required and should never be disabled by adding required = TRUE.
---

> They make it possible for a module to define new urls and pages within the site (hook_menu), to add content to pages (hook_block), to set up custom database tables (hook_schema), and more.This pagelists the hooks provided in the core, but modules can define hooks of their own.

Needs a space (after `This page`):

They make it possible for a module to define new urls and pages within the site (hook_menu), to add content to pages (hook_block), to set up custom database tables (hook_schema), and more.This page` `lists the hooks provided in the core, but modules can define hooks of their own.
---

Testing with SimpleTest

> We are just getting started with testing, so we will write very basic tests that ascertain if our four main hooks function as expected.

I think we should ommit this sentence.

~Geoff

**Comment by BWPanda** [comment]
I've fixed all these things except the last one. That I think needs reviewing by @quicksketch or @jenlampton

**Comment by jenlampton** [comment]
For Testing with SimpleTest? Yes, I think it's fine to omit that sentence. We've got other simpletest documentation IIRC.

**Comment by BWPanda** [comment]
Thanks! Removed.

**Comment by serundeputy** [comment]
For the `example hook` TBD section here is a first pass at an example `hook_menu`

### Some Examples of hooks

* `hook_menu` allows you to define a menu item that Backdrop will respond to at a path
  * If you are writing a module named `my_module` then you can define some path(s) where the module will provide content, user facing forms, or admin config forms with `hook_menu`. Here is an example where we want to consume a feed from an external data source:
```php
/**
 * Implements hook_menu().
 */
function my_module_menu() {
  $items['my-path'] = array(
    'title' => 'My Feed',
    'description' => 'Get data from another website feed, parse it and display it on our Backdrop site.',
    'page callback' => 'my_module_get_data',
    'access callback' => TRUE,
  );
  return $items;
}
```

Let's break down the elements here:

*     `'title' => 'My Feed',` 
  * Sets the title on the page, replace `My Feed` with the title you want for your page.
* `'description' => 'Get data from another website feed, parse it and display it on our Backdrop site.',`
  * Describe the page you are going to display to users.
* ` 'page callback' => 'my_module_get_data',`
  * This tells backdrop about the callback function to use for the page.  When Backdrop receives a request in this case at `example.com/my-path` the hook `my_module_menu` will tell that request to use the callback function in this case `my_module_get_data`.
  * You would then define the function `my_module_get_data` later in the `my_module.module` file.  That might look something like this:

```php
/**
 * Callback function for the path my-path.
 * Process the data for the feed and define output markup.
 * 
 * return string $markup
 *   The $markup to return for the page request to /my-path
 */
function my_module_get_data() {
  // Make request to external data feed, parse, and store in $markup variable.  

  return $markup;
}
```

* `'access callback' => TRUE,`
  * The access callback to use for this path.  In this case `TRUE` indicates that anyone including anonymous users can see the content at this path.

**Comment by serundeputy** [comment]
I think I just scope creeped this.  @BWPanda has completed the ask here.  Closing and opening separate issue for new ask.

Thanks @BWPanda !
