### ISSUE TITLE
CSS Coding Standards page has conflicts

### ISSUE THREAD

**Issue by oadaeh** [backdrop-ops/api.backdropcms.org#39]
On the CSS Coding Standards page (https://api.backdropcms.org/css-standards), specifically in the Format -> Properties section (https://api.backdropcms.org/css-standards#format), there is this statement:
> When hex values are used for colors, use lowercase and, if possible, the shorthand syntax, e.g. #aaa. Colors may be expressed with any valid CSS value, such as hex value, color keyword, rgb() or rgba(). Note that IE8 does not support all color syntaxes and will require a fallback value.

In the example beneath it, there is this:
> color: #ffffff; /* Always use 6-digit hex codes. */

**Comment by serundeputy** [comment]
Thanks @oadaeh 
I've removed the line: `color: #ffffff; /* Always use 6-digit hex codes. */`.

https://api.backdropcms.org/css-standards

closing.  Feel free to reopen if necessary.

**Comment by wesruv** [comment]
Ha, that's nutty. I prefer shorthand FWIW, the only reason this is potentially an issue is because it's easier to grep/search for if we always do it one way or the other.

Good catch @oadaeh!
