### ISSUE TITLE
The API site says sytems_settings_form is deprecated.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/api.backdropcms.org#40]
On: https://api.backdropcms.org/converting-modules-from-drupal in the  `Replacing system_settings_form()` section.

It says that `system_settings_form` is deprecated, but I don't think it is anymore.

Issue where systems_settings_form was brought back:
https://github.com/backdrop/backdrop-issues/issues/675

**Comment by jenlampton** [comment]
updated: https://api.backdropcms.org/converting-modules-from-drupal
