### ISSUE TITLE
Use the new theme from backdropcms.org

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/api.backdropcms.org#42]
Once we have the new theme ready for backdropcms.org we should put that theme on the API site as well. 

When we do, we should make sure that headings are bold, as requested in this tweet:
https://twitter.com/jackbravo/status/853772998645616640

**Comment by BWPanda** [comment]
@jenlampton It looks to me like this is done now. Can you confirm?

**Comment by jenlampton** [comment]
Yes, and thank you for cleaning up the queue :)
