### ISSUE TITLE
Site menu messed up on phone

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#47]
When viewing the API site (any page) on my Android phone (using Firefox or Chrome), the site menu (between the search box and the 'stay connected' block) is messed up. When you click on it to expand it, it expands over or under the surrounding page elements. Not only does it look bad, but some links cannot be clicked on because they're too low in the z-index.

Here's a screenshot:
[![Screenshot_20180423-230854.png](https://s9.postimg.cc/eta51zn8f/Screenshot_20180423-230854.png)](https://postimg.cc/image/odtrovckb/)

**Comment by jenlampton** [comment]
I'd like to tackle this in this wee's Backdrop website sprint :)

**Comment by BWPanda** [comment]
I just came to bookmark this myself for the same reason :smile: But all yours @jenlampton!

**Comment by jenlampton** [comment]
@BWPanda if you want it you can have it!

**Comment by BWPanda** [comment]
Here's a PR that should (hopefully) fix this: https://github.com/backdrop-ops/api.backdropcms.org/pull/76 (it's my first time doing a PR with config changes!)

I started trying to fix the menu with CSS, but then realised that we don't even need the hamburger menu on the API site at all, since on small screens the menu is displayed below the content, so there's no worry about having it always fully visible. So I just turned off the hamburger menu and added some styling to remove the `absolute` position of the menu on small screens.

**Comment by BWPanda** [comment]
Here's an 'after' screenshot:

![image](https://user-images.githubusercontent.com/2385329/69432925-4df39380-0d43-11ea-963b-2b23d721a5a4.png)

**Comment by jenlampton** [comment]
This looks fantastic @BWPanda! merged :) and thank you!!!
