### ISSUE TITLE
Add extra functions to Field Formatter API page

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#49]
On the [Field Formatter API](https://api.backdropcms.org/api/backdrop/core%21modules%21field%21field.api.php/group/field_formatter/1) page it lists the following functions:

- `hook_field_formatter_info()`
- `hook_field_formatter_info_alter()`
- `hook_field_formatter_prepare_view()`
- `hook_field_formatter_view()`

I think we should also add the following functions:

- `hook_field_formatter_settings_form()`
- `hook_field_formatter_settings_summary()`

**Comment by BWPanda** [comment]
It seems that this page is generated automatically based on the documentation in `field.api.php`. The two missing functions are in `field_ui.api.php` however...

We should therefore add a note about the two UI functions manually around line 1018 in https://api.backdropcms.org/api/backdrop/core%21modules%21field%21field.api.php/1

**Comment by BWPanda** [comment]
[PR](https://github.com/backdrop/backdrop/pull/2908) created.

**Comment by klonos** [comment]
PR look good. RTBC 👍

**Comment by jenlampton** [comment]
This PR needs to be against Backdrop core itself. (All the API site does is read core, and then turn it into a web-accessable version.) Can you create an issue, tag it with "documentation", and move the PR over to that repo?

**Comment by BWPanda** [comment]
THis has been fixed in https://github.com/backdrop/backdrop-issues/issues/4223
