### ISSUE TITLE
Wrong reference to Backdrop 8.x

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/api.backdropcms.org#52]
There is a reference to Backdrop 8.x which I guess should be to Drupal 8.x. This is in https://api.backdropcms.org/doc-standards, in the **hook_menu() page router callback functions** section within https://api.backdropcms.org/doc-standards#functions

**Comment by BWPanda** [comment]
There are actually at least 4 references to 'Backdrop 8' on that page (using browser's 'Find...' function). Looks like this page needs some updating...

**Comment by BWPanda** [comment]
I believe these have all been removed/fixed. Please re-open if I'm mistaken.
