### ISSUE TITLE
Standardise `@file` docblock summary wording for `.admin.inc` files

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#54]
Currently different modules use different wording for the `@file` docblock summary in `.admin.inc` files, even in core. Can we agree on a standard and add it to https://api.backdropcms.org/doc-standards#file (like with `.install` files)?

Here's examples of what I mean:
- "Admin page callbacks for the [MODULE] module."
  - Block, Comment, Contact
- "Administration page callbacks for the [MODULE] module."
  - Book
- "Admin menu callbacks and theme functions for [MODULE] module."
  - CKEditor
- "Administrative pages and callbacks for the [MODULE] module."
  - Config
- "[MODULE] administration code."
  - Date
- "Administrative page callbacks for the [MODULE] module."
  - DBLog

(That's just the first 14 modules in core)

**Comment by BWPanda** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/2907).

I went with "Admin page callbacks for the [MODULE] module." as that was the most popular wording from my original post above, in addition to what the System module uses.

If there's no objections to this, then once the PR gets committed we can update the API documentation accordingly.

**Comment by klonos** [comment]
Thanks @BWPanda 👍 ...shouldn't this PR be against Backdrop core?

Otherwise RTBC (you know I'm a sucker for consistency 🙂)

**Comment by BWPanda** [comment]
@klonos The PR *is* against core. The issue was just posted here as the API site is where the standard is/should be documented.

**Comment by klonos** [comment]
Ah, gotcha 👍 ...I have already approved the PR, but there is no issue agains any core milestone for me to RTBC :/

**Comment by BWPanda** [comment]
Thanks @klonos. I've merged https://github.com/backdrop/backdrop/pull/2907 into Backdrop core 1.x and 1.17.x (since this is a documentation task and not a new feature).
