### ISSUE TITLE
There is some stray merge conflict marking in bootstrap.inc

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/api.backdropcms.org#55]
https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/1

Line 3186 onwards:

```
<<<<<<< HEAD
    // If the path in destination is an array, it must have been set through an
    // invalid "q" parameter in backdrop_parse_url().
    $destination_parts = backdrop_parse_url($_GET['destination']);
    if (is_array($destination_parts['path'])) {
      $sanitized_keys = array('q');
    }

    // If there is a query string, check its query parameters.
=======
    // If there is a query string, check its query parameters.
    $destination_parts = backdrop_parse_url($_GET['destination']);
>>>>>>> ae93eccb2aafb58e887ec5acf4c46b53b6963f67
```

**Comment by docwilmot** [comment]
Note this seems to have affected the parsing of the documentation: none of the functions after that code block above show up on searching the API site! e.g `backdrop_autoload()`

**Comment by herbdool** [comment]
Seems like the second part matches upstream.

**Comment by quicksketch** [comment]
Nice call @docwilmot! So the API site has a separate Git checkout of the code. On cron jobs, it does a `git pull origin 1.x`. What happened here is that something must have been force-pushed to the 1.x branch. When the API site tried to pull down, it conflicted with the previous commit before the force push.

Note we shouldn't ever be force-pushing to the 1.x branch, but it looks like I was the one who did it! Doh!

To fix this:
```
ssh api@api.backdropcms.org
cd ~/backdrop-code-to-index
git reset origin/1.x --hard
git pull origin 1.x
```

Then cron should continue pulling down as usual. Nice spotting!
