### ISSUE TITLE
Form API Reference page/link

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#6]
current status: Need to add the following HTML5 elements:
- [ ] search
- [ ] number
- [ ] email
- [ ] help?

---
original issue:

I often use the [Form API Reference](https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7) page on api.drupal.org. I can't find the equivalent page on api.backdropcms.org - does it not exist, or is the link hidden somewhere?

If it doesn't exist, I'd like to ask that it be created.
If it does exist, I'd like to ask that a link be placed somewhere so it can be found (api.drupal.org has a link [here](https://api.drupal.org/api/drupal)).

**Comment by docwilmot** [comment]
Hi, to return to this, were you suggesting that instead of a single html document, that each property, for example, be a node? Like an "actions" node with a "descriptions", "properties" and "usage example" fields?
I like the idea, but considering that these would change  very rarely, is that necessary? What would be the advantage?

**Comment by cellear** [comment]
I didn't mean to express any opinion (yet) on how the information should be structured.  I was just opining that I thought it was silly to be writing static HTML files to document our content management system!  While it's not always a good idea to eat your own dog food (as we've wrestled with a bit in the Forums discussion) I think in this case we absolutely should.  These are just HTML docs; Backdrop handles them perfectly right out of the box.

We just need to decide how to include the content nodes.  I've always been astonished at how hard this seems to be to do in Drupal -- is there some secret trick that everybody except me knows?  Writing an install profile or an update hook, or wrestling with Feeds or Migrate seems like a difficult way to do something that every single project needs.

**Comment by docwilmot** [comment]
> We just need to decide how to include the content nodes.

Sorry, I dont understand what that means.

**Comment by cellear** [comment]
I mean instead of having 3 HTML files checked into the repo, the API site (if it were to contain the same information) should just have 3 nodes, living in the database.  Except then we lose the ability to check it into the repo.  Don't we?

**Comment by quicksketch** [comment]
> I mean instead of having 3 HTML files checked into the repo, the API site (if it were to contain the same information) should just have 3 nodes, living in the database.

I'm all for this. The way Form API is locked away in a Git repository that no one can find is a hold-over from when everything was managed with CVS. Drupal even has a [marketing](http://cgit.drupalcode.org/documentation/tree/)(!) directory in Git. Not exactly the right tool for the audience there.

With the mixing of code-provided docs and node-provided docs we have already, I think it makes sense for us to maintain this simply as a revisioned node rather than as an HTML file in a repo.

**Comment by docwilmot** [comment]
Please review: https://api.backdropcms.org/node/41642
Needs table tag added to filter

**Comment by quicksketch** [comment]
Sweet, I added the table tag along with others you may need writing docs (p, div, pre, etc). The table overall looks okay, but it blows out the side of the page. I wonder how we could CSS this to make it look more presentable. I'll try a few things and see if I can get it to be more readable.

**Comment by BWPanda** [comment]
I don't like api.drupal.org's solution of using `word-break: break-all;`: https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7

Got me thinking though, what about making the column headings more vertical so they take up less space? Something like this: http://css-tricks.com/rotated-table-column-headers/

Also, we can get rid of the duplicated 'th' column on the right of the table (not needed).

**Comment by docwilmot** [comment]
i think either wrap the table in a 100% width <div> with overflow-x: scroll alone; or also with a fancy jquery solution that fixes the first column.

**Comment by docwilmot** [comment]
> I added the table tag along with others you may need writing docs (p, div, pre, etc)

Header tags missing (H1, H2 etc)

**Comment by quicksketch** [comment]
I added some CSS and a JS adjustment to make those table headers rotate per @BWPanda's suggestion: https://api.backdropcms.org/node/41642

I also added the autocomplete search box that can be used to either A) autocomplete a function/file/other or B) be used to search the site documentation.

The Form API Reference page always has seemed rather important, should we give it an URL alias?

**Comment by quicksketch** [comment]
> The Form API Reference page always has seemed rather important, should we give it an URL alias?

And put it into the Handbook menu.

**Comment by docwilmot** [comment]
Very nice!
Will work on removing the Drupalisms. 
Is there anything API-wise that should be added or removed from this though? Any D7 to BD API changes?

**Comment by quicksketch** [comment]
Let's see, we have new HTML5 elements:

- search
- number
- email

Number has a few new properties that match the HTML5 spec: #min, #max, and #step. Other than those, I think we're pretty much the same.

**Comment by quicksketch** [comment]
I think we should add a URL alias to this page as well. Just `formapi` maybe? I started a larger discussion on aliases over here: https://github.com/backdrop-ops/api.backdropcms.org/issues/14.

**Comment by BWPanda** [comment]
> I added some CSS and a JS adjustment to make those table headers rotate per @BWPanda's suggestion...

That looks awesome! :+1: 

> >The Form API Reference page always has seemed rather important, should we give it an URL alias?

> And put it into the Handbook menu.

Yes please. Whatever the alias is doesn't really matter (just makes the URL look nicer, can be discussed further in that other issue anyway), but making the page find-able would be good. I like the menu organisation discussion happening in https://github.com/backdrop-ops/api.backdropcms.org/issues/3#issuecomment-71902056 but in the meantime, or even in addition to those eventual changes, could we add a Form API link to the table here?: https://api.backdropcms.org/api/backdrop/groups (seems like a logical place, next to 'Form builder functions' and 'Form generation'...)

**Comment by quicksketch** [comment]
> in the meantime, or even in addition to those eventual changes, could we add a Form API link to the table here?

All of those "topics" are code-generated from PHP docblocks. So if we want to add a link, we'd have to do it *inside* of Form Builder Functions or Form Generation, and do it via a PR to the Backdrop project.

Or alternatively, we could regenerate that page of "Topics" using nodes or menu links, but I have a feeling that'd get unwieldy pretty quick.

**Comment by BWPanda** [comment]
I've gone ahead and added a URL alias and menu item: https://api.backdropcms.org/form_api
Can be changed later if necessary, but thought it'd be good to have at least something now.

**Comment by quicksketch** [comment]
Sounds good to me. We'll need to get Redirect module on there eventually.

**Comment by serundeputy** [comment]
@BWPanda @docwilmot @cellear @quicksketch 

More work to be done here?  Looks like things are in a pretty good state.  I'd say close this and open up follow ups if things come up.

**Comment by docwilmot** [comment]
That page still has some issues. Its still missing some new form elements. See above https://github.com/backdrop-ops/api.backdropcms.org/issues/6#issuecomment-72285772 and the new `help` element, plus its still a cut and paste of a huge static file and we havent decided if individual nodes may be better. So I'm not sure if its closable yet. @jenlampton thoughts?

**Comment by BWPanda** [comment]
I've gone ahead and fixed the doubling of the bullet points as per https://github.com/backdrop-ops/api.backdropcms.org/issues/6#issuecomment-72288539 above.

**Comment by jenlampton** [comment]
> we haven't decided if individual nodes may be better

It looks like we have decided to replace the old /documentation HTML files directory with three nodes, and we have those nodes. Was there another decision that needed to be made?

**Comment by docwilmot** [comment]
> Was there another decision that needed to be made?

Just re-read the issue, and no, seems we just need to add the new stuff. 

My initial thought was that instead of a huge HTML document, we could have individual nodes for each FormAPI element and create some views and tables to display them. It would make it easier to add and edit these elements, but does increase complexity somewhat. If this is worth considering, we could create a new issue.

**Comment by BWPanda** [comment]
Closing this now, with follow-up of building better FAPI page (with missing elements added) happening in https://github.com/backdrop-ops/api.backdropcms.org/issues/66
