### ISSUE TITLE
Typo on change record page about Layouts

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/api.backdropcms.org#63]
On the page https://api.backdropcms.org/change-records/new-layout-module-implements-drag-drop-model-building-layouts, in the section **No automatic path-based suggestions for page templates**, there is a typo (see the double "pre":

> ... recreate the suggestion via hook_**prepre**process_page()

should be:

> ... recreate the suggestion via hook_**pre**process_page()

**Comment by serundeputy** [comment]
updated: https://api.backdropcms.org/change-records/new-layout-module-implements-drag-drop-model-building-layouts

thanks @olafgrabienski
