### ISSUE TITLE
Missing 'URL' type in Form API Reference

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#65]
On the [Form API Reference](https://api.backdropcms.org/form_api) page, there's a link to a 'URL' type (https://api.backdropcms.org/form_api#url), but it doesn't lead anywhere as the corresponding section doesn't exist. Unfortunately I don't know enough to create/write this myself...

**Comment by BWPanda** [comment]
Once https://github.com/backdrop-ops/api.backdropcms.org/issues/66 is done then this should happen automagically :wink: 

Closing as a duplicate.

**Comment by BWPanda** [comment]
Hmm, maybe not automatically. But certainly easier to wait until https://github.com/backdrop-ops/api.backdropcms.org/issues/66 is done before adding this.

**Comment by jenlampton** [comment]
I added URL: https://api.backdropcms.org/form_api https://api.backdropcms.org/form_api#url

**Comment by BWPanda** [comment]
Thanks for this @jenlampton, but there are still a few places that need updating (e.g. https://api.backdropcms.org/form_api#required). But I'd be happy just to leave this until I've done the new content types etc. (hoping to start on that soon) then all this linking/referencing will happen automatically.

**Comment by jenlampton** [comment]
I've updated all the individual property descriptions to include URL. It could be a long time before we get a new Form API page done, so I've made the updates so the current page is more accurate today.
