### ISSUE TITLE
Form API: Move vertical tabs and weight down to "special" elements

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/api.backdropcms.org#77]
Since vertical tabs is not a field and #weight has special properties, I'm going to move them down to the "special" section of the form API page.

**Comment by jenlampton** [comment]
Reference page updated: https://api.backdropcms.org/form_api
Copy of HTML also committed, for sanity.

**Comment by BWPanda** [comment]
> Copy of HTML also committed, for sanity.

@jenlampton I believe the [file you committed](https://github.com/backdrop-ops/api.backdropcms.org/blob/master/form_api.html) is already available [here](https://github.com/backdrop-ops/api.backdropcms.org/blob/master/www/documentation/forms_api_reference.html) (albeit needing updating). Perhaps you could re-save it in the right folder and in the right format (e.g. the full HTML page, not just the Body field)...?

**Comment by jenlampton** [comment]
> Perhaps you could re-save it in the right folder 

If we're not showing the contents of this file directly, it should be outside the docroot. From the commit messages, it looks like that wasn't an option when this dir was initially added. I'll move it. see https://github.com/backdrop-ops/api.backdropcms.org/issues/78 

> and in the right format

It seems to me that the "right format" is the one we are going to use, which would only be the body field. I'm not sure why a whole page was committed before...  I'll see if I can find the commit history. 

Either way, these changes are unrelated to this issue (which was to update the body field). So. closing. :)
