### ISSUE TITLE
New Form API page updates

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/api.backdropcms.org#89]
As I'm adding the content to the new Form API page, I'm realising the need for a few more changes:

- [x] Automate the display of values for the `#type` property
      The whole point of fixing this page is to make it easier to add/edit content. I.e. not having to search through the page to find all the instances of where a change needs to be made. Since the `#type` property lists all the elements as its values, I figured it'd be nice to automate this so people adding a new element don't have to update this part manually.

- [ ] ~~Add an extra field to FAPI Properties to determine which ones should be hidden from the table at the top of the page
      For example, none of the `#ajax[...]` properties appear in the table...~~
      This can be discussed and decided in https://github.com/backdrop-ops/api.backdropcms.org/issues/93

- [x] Make it easier to add Properties to Elements initially
      When doing the initial setup of the Element nodes, I have to manually create a paragraph item for each property of that element. As each element can have dozens of properties, and as there are dozens of elements, this is tedious. I found a way to make this easier - setup a new, simple checkboxes list that I can tick which properties an element, then on save it converts those checkboxes into the actual paragraphs entity. This is temporary, just for the initial creating of content from the existing HTML page. Once that's done, I'll remove this functionality again.

- [x] Revert the changes above
      Make a seperate commit later that undoes the changes above re. making it easier to add properties to elements.

- [x] Fix duplicate IDs
      When there's an element and a property with the same name, they're given the same ID (e.g. `markup, submit, value, weight`). One fix could be to suffix all element IDs with `_element` and all properties with `_property`, but that'll break existing permalinks... Otherwise we need a way to allow specifying a custom ID value.

- [x] Change URL of Form API page
      The current URL is so you can see both the old and new pages at the same time, but once this is ready we should replace the existing page with the new one (i.e. give the new page the `form_api` URL and the old one something like `form_api_old` (until we actually delete it)).

Ticked items above are in the linked PR.

**Comment by BWPanda** [comment]
Oops, pushed changes in PR to live site so I can continue adding content easier, but didn't mean to close this.

**Comment by BWPanda** [comment]
Additional PR for the above items (plus a few extra things I fixed along the way) ready to be reviewed (though I suspect it might be easier to just push this and then test on the live site...). @jenlampton what do you think?

**Comment by jenlampton** [comment]
Go ahead!

**Comment by jenlampton** [comment]
🎊
