### ISSUE TITLE
There is no record of the removed element_validate_integer_positive()

### ISSUE THREAD

**Issue by juanolalla** [backdrop-ops/api.backdropcms.org#9]
Porting Email module, I found a fatal error due to the use of this function that no longer exist in form.inc. I didn't know the reason, and I used the Change Record search to locate it, but there weren't results for "element_validate_integer_positive".

@quicksketch explained me later in IRC that it was replaced by https://api.backdropcms.org/api/backdrop/core!includes!form.inc/function/form_validate_number/1, and that I had to use $element = array('#type' => 'number', '#min' => 0, '#step' => 1) to validate it.

I think we should add this info to the Change Records to allow developers finding easily the solution to this problem.

**Comment by docwilmot** [comment]
Hi can you create an issue on https://github.com/backdrop/issues/issues so this can be tagged so we dont forget it. Thanks for reporting this. There are a few other changes that are missing from the change records, working on that still.

**Comment by quicksketch** [comment]
Let's tack this onto https://github.com/backdrop/backdrop-issues/issues/108, the original issue for creating the e-mail HTML5 element. I've marked it needs change notice and copied @juanolalla's post into it. Thanks @docwilmot!

I suppose we can close this then if it's being tracked in the other issue.
